# Generated by Django 5.0.6 on 2024-07-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fileupload',
        ),
    ]
